from datetime import date

# Define the reporting periods covered by the synthetic Actual dataset.
# FY2025 provides prior-year comparatives, while Jan-Aug 2026 represents current-year Actuals as at the management reporting date.

ACTUAL_START_DATE = date(2025,1,1)
ACTUAL_END_DATE = date(2026,8,31)

REPORTING_DATE = date(2026,8,31)

PRIOR_YEAR = 2025
CURRENT_YEAR = 2026

# Use a fixed random seed so the synthetic transaction dataset can be reproduced consistently across development and testing runs.
RANDOM_SEED = 42


# Use a fixed number of transactions per business day for the first version.
# Transaction frequency can be made more account-specific in a later step.
TRANSACTIONS_PER_BUSINESS_DAY = 40

# Approximate the share of operational activity generated by each legal entity. The weights sum to 100% and drive transaction-level entity sampling.
ACTUAL_ENTITY_WEIGHTS = {
    "ENT01":0.55,
    "ENT02":0.18,
    "ENT03":0.15,
    "ENT04":0.12
}

# Define broad transaction-value ranges by P&L account class. These ranges create realistic variation at transaction level.
ACCOUNT_AMOUNT_RANGES = {
    "4":(1_000,25_000), # Revenue
    "5":(500,10_000),   # Cost of Revenue
    "6":(250,7_500)     # Operating Expenses
}

# Define the approximate transaction frequency mix across the main P&L account classes. These weights control record frequency, not total value.
ACCOUNT_CLASS_TRANSACTION_WEIGHTS = {
    "4":0.30,   # Revenue
    "5":0.20,   # Cost of Revenue
    "6":0.50,   # Operating Expenses
}

# Define the high-level management P&L targets that the generated Actual transactions will later be calibrated to.
# FY2025 represents the full prior year, while FY2026 covers Jan-Aug only as at the reporting date.
ACTUAL_PNL_TARGETS = {
    2025:{
        "revenue": 72_000_000,
        "gross_margin": 0.74,
        "ebitda_margin": 0.13,
    },
    2026:{
        "revenue": 52_500_000,
        "gross_margin": 0.75,
        "ebitda_margin": 0.16,
    }
}

# Convert the high-level margin assumptions into target P&L amounts.
# These values will later be used to calibrate the generated GL transactions.
ACTUAL_PNL_AMOUNTS = {}

for year, assumptions in ACTUAL_PNL_TARGETS.items():

    revenue = assumptions["revenue"]

    cost_of_revenue = revenue * (1 - assumptions["gross_margin"])

    gross_profit = revenue - cost_of_revenue

    ebita = revenue * assumptions["ebitda_margin"]

    operating_expenses = gross_profit - ebita

    ACTUAL_PNL_AMOUNTS[year] = {
        "revenue": revenue,
        "cost_of_revenue": cost_of_revenue,
        "gross_profit": gross_profit,
        "operating_expenses": operating_expenses,
        "ebitda": ebita
    }

# Define plausible journal types by broad P&L account class so synthetic transactions resemble entries
# originating from a finance ERP environment.
JOURNAL_TYPES_BY_ACCOUNT_CLASS = {
    "4": ["AR Invoice", "Revenue Journal"],
    "5": ["AP Invoice", "Accrual Journal"],
    "6": ["AP Invoice", "Payroll Journal", "Expense Journal"]
} 

# Define each legal entity's functional currency.
ENTITY_LOCAL_CURRENCY = {
    "ENT01":"GBP",
    "ENT02":"EUR",
    "ENT03":"EUR",
    "ENT04":"EUR"
}

# Historical monthly average EUR-to-GBP exchange rates from the Bank of England.
# Each rate represents the GBP value of EUR 1.00.
GBP_PER_EUR_MONTHLY = {
    2025:{
        1: 0.8389,
        2: 0.8307,
        3: 0.8375,
        4: 0.8541,
        5: 0.8438,
        6: 0.8498,
        7: 0.8652,
        8: 0.8658,
        9: 0.8691,
        10: 0.8716,
        11: 0.8797,
        12: 0.8750
    },
    2026: {
        1: 0.8678,
        2: 0.8708,
        3: 0.8665,
        4: 0.8692,
        5: 0.8655,
        6: 0.8637,
        7: 0.8537,
        8: 0.8560,
    }
}

# Define controlled data-quality exceptions that will be injected into the raw 
# Actual dataset so the SQL staging layer can detect and handle them later.
DUPLICATE_TRANSACTION_COUNT = 10
MISSING_REGION_COUNT = 8
INVALID_COST_CENTRE_COUNT = 6
CURRENCY_MISMATCH_COUNT = 5


